kleveross/ormb

- README.md
Add usage.
Fixes #
Reference to #
/cc @ddysher @supereagle @codeflitting 
```release-note
NONE
```
> feat: Add usage in readme

- examples/PMML-model/model/single_audit_mlp.pmml
- examples/PMML-model/ormbfile.yaml
- pkg/consts/consts.go
- pkg/model/loader.go
- pkg/ormb/ormb.go
- Add an example for PMML
- Refactor the directory structure of the model bundle
- Mainly move the ormbfile.yaml to the upper directory
Fixes #7 
Reference to #
/cc @supereagle @ddysher @codeflitting 
```release-note
NONE
```
> feat: Refactor the directory sturcture of model bundle

- README.md
- docs/tutorial.md
Add quick start
Fixes #4 
Reference to #
/cc @ddysher 
```release-note
NONE
```
> feat(docs): Add quick start

- cmd/ormb/cmd/export.go
- cmd/ormb/cmd/login.go
- cmd/ormb/cmd/prerun.go
- cmd/ormb/cmd/pull.go
- cmd/ormb/cmd/push.go
- cmd/ormb/cmd/root.go
- cmd/ormb/cmd/save.go
- pkg/ormb/ormb.go
We keep the cache and config.json in `$HOME/.ormb/` by default. But users can customize it using `rootPath` in `$HOME/.ormb/config.yaml`
Fixes #
Reference to #
```release-note
NONE
```
> feat(cmd): Support custom cache

- README.md
- docs/spec-v1alpha1.md
- pkg/consts/consts.go
Add model config v1alpha1 specification, compared with the internal manifest definition:
- Add extensibility for dataset and training. Currently we only support git repo but keep the extensibility for other sources.
- Remove resource limits in the manifest
Fixes #3 
Reference to #
/cc @ddysher @codeflitting 
```release-note
NONE
```
> feat(docs): Add model config spec

- cmd/ormb/cmd/login.go
- cmd/ormb/cmd/option.go
- cmd/ormb/cmd/prerun.go
- cmd/ormb/cmd/pull.go
- pkg/oci/client.go
- pkg/oci/client_opts.go
Fixes #
Reference to #
```release-note
NONE
```
> feat(cmd): support plain HTTP

- cmd/ormb/cmd/export.go
- cmd/ormb/cmd/login.go
- cmd/ormb/cmd/pull.go
- cmd/ormb/cmd/push.go
- cmd/ormb/cmd/save.go
- pkg/ormb/ormb.go
Fixes #
- It should not panic even if there is an error.
Reference to #
```release-note
NONE
```
> fix(cmd): Remove panic logic

- .gitignore
- cmd/ormb/cmd/remove.go
- pkg/oci/client.go
- pkg/ormb/ormb.go
Support remove model from the local filesystem cache.
Fixes #14 
Reference to #
/cc @ddysher @simon-cj 
```release-note
NONE
```
> feat(cmd): Support remove cmd

- README.md
- examples/SavedModel-fashion/ormbfile.yaml
- pkg/model/types.go
- pkg/oci/client.go
Print format information for model when saving/exporting.
Fixes https://github.com/caicloud/ormb/issues/13
Reference to #
/cc @ddysher 
```release-note
NONE
```
> feat: Print format in stdout

- examples/SavedModel-fashion/training-serving.ipynb
- pkg/exporter/exporter.go
- pkg/model/types.go
- pkg/oci/cache.go
- pkg/ormb/ormb.go
- pkg/parser/parser.go
- pkg/saver/saver.go
Export metadat when we call `ormb export xxx`
Fixes #27 
Reference to #
```release-note
NONE
```
> feat: Export metadata

- .gitignore
- .goreleaser.yml
We are using gorelease https://github.com/goreleaser/goreleaser/ to release our ormb. This PR is to add the corresponding config yaml file for it.
https://github.com/caicloud/ormb/releases/tag/v0.0.1
Fixes #
Reference to #
/cc @ddysher 
```release-note
NONE
```
> feat: Add goreleaser config yaml

- OWNERS
Fixes #
Reference to #
```release-note
NONE
```
> feat: update OWNERS

- extern-sdk/python/.gitignore
- extern-sdk/python/OWNERS
- extern-sdk/python/setup.py
Release the python package to pypi
Fixes #49 
Reference to #
```release-note
NONE
```
> feat: Release python package in pypi

- Makefile
- README.md
Use docker.io in the makefile
Fixes #54 
Reference to #
/cc @simon-cj @codeflitting 
```release-note
NONE
```
> feat: Use docker.io in Makefile

- pkg/model/types.go
Fixes #
https://github.com/caicloud/ormb/issues/57
Reference to #
/cc @gaocegege @ddysher 
```release-note
NONE
```
> feat: Support signature in metadata data structure

- .travis.yaml
- README.md
Add Travis CI configuration file:
- Run unit tests
- Compile
- Run goreleaser if necessary.
Fixes #59 #43 
Reference to #
```release-note
NONE
```
>  feat(ci): Add Travis CI config

- .travis.yml
- README.md
Add coveralls in CI
Fixes #
Reference to #
```release-note
NONE
```
> chore(ci): Add coveralls

- pkg/oras/client.go
- pkg/oras/client_test.go
Fixes #
Reference to #
```release-note
NONE
```
> feat: Add client test

- .gitignore
- pkg/oras/cache/cache_suite_test.go
- pkg/oras/cache/cache_test.go
Add test for cache package
Fixes #
Reference to #
```release-note
NONE
```
> feat: Add test for cache

- pkg/model/types.go
Fixes #
https://github.com/caicloud/ormb/issues/62
Reference to #
```release-note
NONE
```
> feat(pmml): Support PMML signature

- docs/spec-v1alpha1.md
Fixes #
Reference to #
```release-note
NONE
```
> feat: Update spec's Tensor

- .travis.yml
- pkg/exporter/exporter_suite_test.go
- pkg/exporter/exporter_test.go
- pkg/saver/saver_suite_test.go
- pkg/saver/saver_test.go
Make test coverage to 70%
Fixes #6 
Reference to #
```release-note
NONE
```
>  feat: Add more tests

- cmd/ormb-storage-initializer/cmd/root.go
Remove the logic about removing version directory in storage initializer.
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> feat: Remove useless logic

- README.md
Fixes #
Reference to #
```release-note
NONE
```
> fix(link): error link

- .goreleaser.yml
- Makefile
Fixes #80 
Reference to #
```release-note
NONE
```
> chore: Disable CGO by default

- build/ormb-storage-initializer/Dockerfile
- cmd/ormb-storage-initializer/cmd/pull-and-export.go
- cmd/ormb-storage-initializer/cmd/root.go
- docs/tutorial-serving-seldon.md
There may be some bugs if we use root command directly. Then we should use the subcommand `pull-and-export`
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> feat(initializer): Use subcommand to keep the real logic

- README.md
Add CLI demo in README
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> feat: Add CLI demo in readme

- Makefile
Fixes #
Reference to #
```release-note
NONE
```
> fix(Makefile): enable race detection in tests only

- .goreleaser.yml
- README.md
- Revise readme, remove usage
- Remove cgo-enable in goreleaser to support cross-compiling.
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> chore: Revise README and remove cgo in goreleaser

- OWNERS
Add @simon-cj as an approver.
Fixes #
Reference to #
```release-note
NONE
```
> chore: Update owners

- README.md
Fixes #
Reference to #
```release-note
NONE
```
> feat: Update community section

- cmd/ormb/cmd/prerun.go
- cmd/ormb/cmd/root.go
Close #38 
Fixes #
Reference to #
/cc @simon-cj 
```release-note
NONE
```
> feat: Support loglevel

- pkg/oci/reference.go
When exec ormb save or other cmd, if use ip,there is an error as follow:
```
./bin/ormb save ./examples/SavedModel-fashion 192.168.22.160:30002/release/savedmodel:v1
Using config file: /Users/caicloud/.ormb/config.json
Using /Users/caicloud/.ormb as the root path
[192.168.22.160 30002/release/savedmodel v1]
components: [192.168.22.160:30002/release/savedmodel v1]
suc1
Error: parse 192.168.22.160:30002/release/savedmodel: first path segment in URL cannot contain colon
Usage:
ormb save [flags]
Flags:
-h, --help   help for save
Global Flags:
--config string   config file (default is $HOME/.ormb/config.json)
parse 192.168.22.160:30002/release/savedmodel: first path segment in URL cannot contain colon
```
according to [issue]( …
> fix(oci): Suppport ip for cmd

- .goreleaser.yml
- Makefile
- cmd/ormb-storage-initializer/main.go
- cmd/ormb/main.go
Fixes https://github.com/kleveross/ormb/issues/82
Reference to #
```release-note
NONE
```
> feat(goreleaser): Add release version info for goreleaser 

- Makefile
Fixes #
Reference to #
```release-note
NONE
```
> feat(makefile): Update clever to klever

- pkg/oci/reference.go
- pkg/oras/cache/cache.go
it is more flexible when add more colons.
Fixes #
Reference to #
/cc @gaocegege @simon-cj
```release-note
NONE
```
> chore: move validation to default branch

- examples/Caffe2-model/ormbfile.yaml
- examples/TorchScript-model/ormbfile.yaml
Both of TorchScript and NetDef format can not get inputs and outputs by extract, so when execute ormb push,  must make sure it contain the inputs and outputs， otherwise it can not serving
Fixes #
Reference to #
```release-note
NONE
```
> feat: Update TorchScript and NetDef example model

- examples/GraphDef-model/ormbfile.yaml
Fixes #
Reference to #
```release-note
NONE
```
> feat: Add more metadata for GraphDef example

- pkg/model/types.go
- pkg/saver/saver.go
Signed-off-by: Ce Gao <gaoce.gaoc@bytedance.com>
Support directory structure
Fixes #42 
Reference to #
```release-note
NONE
```
> feat(metadata): Support directory structure

- README.md
- README_zh.md
chore(docs): add chinese version of README
Fixes #
Reference to #122
/cc @gaocegege @simon-cj 
```release-note
NONE
```
> chore(docs): add chinese version of README

- .goreleaser.yml
- OWNERS
- go.mod
- go.sum
- vendor/golang.org/x/sync/semaphore/semaphore.go
- vendor/modules.txt
Signed-off-by: Ce Gao <gaoce.gaoc@bytedance.com>
Fixes #
Reference to #
```release-note
NONE
```
> fix: Fix the goreleaser and vendor

- CONTRIBUTING.md
- LICENSE
- README.md
- README_zh.md
- docs/README.md
- docs/docs_zh/README.md
- docs/docs_zh/introduction.md
- docs/introduction.md
chore(docs): add ormb doc and open source license
Fixes #
Reference to #122 #95
/cc @gaocegege @simon-cj 
```release-note
NONE
```
> chore(docs): add ormb doc and open source license

- .github/workflow/main.yml
fix(ci): add github actions
Fixes #
Reference to #
/cc @gaocegege @simon-cj 
```release-note
NONE
```
> fix(ci): add github actions

- .github/workflows/main.yml
Signed-off-by: Ce Gao <gaoce.gaoc@bytedance.com>
Fix dir name
Fixes #
Reference to #
```release-note
NONE
```
> fix: Fix dir name to workflows

- .github/workflows/main.yml
- Makefile
fix(ci): fix github action ci
Fixes #
Reference to #
/cc @gaocegege @simon-cj 
```release-note
NONE
```
> fix(ci): fix github action ci

- .github/workflows/main.yml
Fixes #
Reference to #
```release-note
NONE
```
> feat: Add coverage

- Makefile
Fixes #
Reference to #
```release-note
NONE
```
> chore(makefile): Update makefile

- .github/workflows/publish.yml
Fixes #
Reference to #
```release-note
NONE
```
> feat(action): Add publish action

- .github/workflows/main.yml
- .github/workflows/publish.yml
Fixes #
Reference to #
```release-note
NONE
```
> fix: Fix publish action version

- .github/workflows/publish.yml
Fixes #
Reference to #
```release-note
NONE
```
> fix: Set tag in publish action

- cmd/ormb-storage-initializer/cmd/pull-and-export.go
Fixes #
Reference to #
```release-note
1. Add Relayout function on ormb-storage-initializer for MLflow model serving storage initializing.
```
> feat(KLV-30): add relayout function for MLflow

- cmd/ormb-storage-initializer/cmd/pull-and-export.go
Fixes #
Reference to #
```release-note
NONE
```
> feat(KLV-30): remove the opaque environment of AWS

- docs/tutorial-serving-seldon.md
Fixes #
Reference to #
```release-note
NONE
```
> docs: update for a better env name

- cmd/ormb/cmd/prerun.go
- cmd/ormb/cmd/util.go
- cmd/ormb/cmd/util_test.go
Compatible with two levels for model ref
two level like: gohabro.io/release:v1
three level like: gohabro.io/release/release:v1
Fixes #
Reference to #
/cc @codeflitting @gaocegege @FogDong 
```release-note
Compatible with two levels for model ref
```
> feat: compatible with two levels for model ref

- .github/workflows/main.yml
- .github/workflows/publish.yml
- pkg/ormb/ormb_test.go
The old usage is deprecating, please ref https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Fixes #
Reference to #
/cc @FogDong @codeflitting 
```release-note
NONE
```
> chore(*): update github action

- .github/PULL_REQUEST_TEMPLATE.md
Update github template
Fixes #
Reference to #
/cc @codeflitting @FogDong 
```release-note
Update github template
```
> chore(*): update github template

- cmd/ormb-storage-initializer/cmd/pull-and-export.go
- cmd/ormb/cmd/pull.go
- cmd/ormb/cmd/push.go
- pkg/oras/client.go
- pkg/oras/interface.go
- pkg/oras/mock/mock.go
- pkg/ormb/mock/mock.go
- pkg/ormb/ormb.go
- pkg/ormb/ormb_test.go
/kind regression
Revert last two commit
Fixes #
Reference to #
/cc @FogDong 
```release-note
Revert last two commit
```
> fix(*): revert last two commit

- examples/GraphDef-model/ormbfile.yaml
/kind bug
/area model
Fix graphdef example
Fixes #
Reference to #
/cc @FogDong @judgeeeeee 
```release-note
Fix graphdef example
```
> fix(examples): fix graphdef example

- pkg/model/format.go
- pkg/model/format_test.go
/kind bug
Skip Others format validate
Fixes #
Reference to #
/cc @FogDong 
```release-note
Skip Others format validate
```
> feat(check): skip Others format validate

- docs/docs_zh/introduction.md
- docs/introduction.md
- docs/spec-v1alpha1.md
- pkg/model/types.go
/kind feature
/area model
update ormb Metrics from `[]Metric` to `map[str][]Metric`
Fixes #
Reference to #
/cc @FogDong @simon-cj 
```release-note
update ormb Metrics from `[]Metric` to `map[str][]Metric`
```
> feat(ormb): update ormb Metrics

- pkg/model/types.go
/kind bug
fix some bug
Fixes #
Reference to #
/cc @FogDong 
```release-note
NONE
```
> fix(type): MetricList type error

- docs/docs_zh/introduction.md
- docs/introduction.md
/kind documentation
/area serving
Fix(docs): fix broken link in doc and format doc
Fix #164 
Fixes #
Reference to #
/cc @simon-cj 
```release-note
Fix(docs): fix broken link in doc and format doc
```
> Fix(docs): fix broken link in doc and format doc

- pkg/model/format.go
/kind bug
For SavedModel, the dir variables maybe is empty, we can not check it forcely.
Fixes #
Reference to #
/cc @FogDong 
```release-note
remove check variables dir for savedmodel
```
> fix(format): remove check variables dir for savedmodel

- pkg/saver/saver.go
- pkg/util/util.go
- pkg/util/util_test.go
/kind feature
/area model
when exec `ormb save` and there are not ormbfile.yaml, generate ormbfile.yaml automatically
Fixes #
Reference to #
/cc @FogDong 
```release-note
None
```
> feat(model): generate ormbfile.yaml automatically

- cmd/ormb/cmd/root.go
/kind bug
The env `rootPath` is not take effect before this PR.
Fixes #
Reference to #
/cc @FogDong 
```release-note
None
```
> fix(config): fix rootPath env

- README.md
- README_zh.md
- docs/README.md
- docs/docs_zh/README.md
- docs/introduction.md
/kind bug
**What this PR does / why we need it**: Fix(docs): fix ormb save command in doc
Fixes #173
Reference to #
/cc @simon-cj 
```release-note
Fix(docs): fix ormb save command in doc
```
> Fix(docs): fix ormb save command in doc

- .github/workflows/publish.yml
Signed-off-by: cegao <ce.gao@outlook.com>
Fixes #
Reference to #
```release-note
```
> feat: Remove coveralls
